[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "#"
    weight = 1